//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int IdObraSocial { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> IdHistoriaClinica { get; set; }
    
        public virtual HistoriaClinica HistoriaClinica { get; set; }
        public virtual ObraSociale ObraSociale { get; set; }
    }
}
